name: Android Distribute

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Load keystore
        run: echo ${{secrets.JKS}} | base64 -d > composeApp/avialog.jks
      - name: Load key.properties
        run: echo ${{secrets.KEY_PROPERTIES}} | base64 -d > key.properties
      - name: Run gradle tests
        run: ./gradlew test
      - name: Build gradle project
        run: ./gradlew build
      - name: Build AAB
        run: ./gradlew bundleRelease
      - name: Distribute app
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: composeApp/build/outputs/bundle/release/composeApp-release.aab